export const SET_TOPLIST_DETAIL = 'SET_TOPLIST_DETAIL';
export const SET_HOME_RECOMMEND = 'SET_HOME_RECOMMEND';

export const SET_PLAYLIST_CATLIST = 'SET_PLAYLIST_CATLIST';
export const SET_TOP_PLAYLIST = 'SET_TOP_PLAYLIST';

export const SET_TOP_SONG = 'SET_TOP_SONG';

export const SET_TOP_ALBUM = 'SET_TOP_ALBUM';

export const SET_HOME_DJ = 'SET_HOME_DJ';

export const INIT_HOME_TOP_ARTISTS = 'INIT_HOME_TOP_ARTISTS';

export const ADD_HOME_TOP_ARTISTS = 'ADD_HOME_TOP_ARTISTS';
