export const SET_AUDIO_IMMEDIATE = 'SET_AUDIO_IMMEDIATE';

export const SET_AUDIO_PREV = 'SET_AUDIO_PREV';

export const SET_AUDIO_NEXT = 'SET_AUDIO_NEXT';

export const SET_AUDIO_CURRENT = 'SET_AUDIO_CURRENT';

export const SET_AUDIO_RUNNING = 'SET_AUDIO_RUNNING';

export const SET_AUDIO_CURRENTTIME = 'SET_AUDIO_CURRENTTIME';

export const SET_AUDIO_BUFFERED = 'SET_AUDIO_BUFFERED';

export const SET_AUDIO_PLAYLIST_CLEAR = 'SET_AUDIO_PLAYLIST_CLEAR';

export const SET_AUDIO_HISTORY_CLEAR = 'SET_AUDIO_HISTORY_CLEAR';

export const SET_AUDIO_PATTERN = 'SET_AUDIO_PATTERN';

export const SET_VOLUME = 'SET_VOLUME';

export const SET_VOLUME_PLUS_TEN = 'SET_VOLUME_PLUS_TEN';

export const SET_VOLUME_SUB_TEN = 'SET_VOLUME_SUB_TEN';

export const SET_BEFORE_MUTED = 'SET_BEFORE_MUTED';

export const SET_LYRIC_TEXT = 'SET_LYRIC_TEXT';
