export const SET_AUDIO_IMMEDIATE = 'SET_AUDIO_IMMEDIATE';

export const SET_AUDIO_RUNNING_TOGGLE = 'SET_AUDIO_RUNNING_TOGGLE';

export const SET_AUDIO_CURRENTTIME = 'SET_AUDIO_CURRENTTIME';

export const SET_AUDIO_PLAYLIST_CLEAR = 'SET_AUDIO_PLAYLIST_CLEAR';

export const SET_AUDIO_HISTORY_CLEAR = 'SET_AUDIO_HISTORY_CLEAR';

export const SET_AUDIO_PATTERN = 'SET_AUDIO_PATTERN';
