export const SET_TOAST = 'SET_TOAST';

export const SET_POPUP_LETTER_TOGGLE = 'SET_POPUP_LETTER_TOGGLE';
export const SET_POPUP_PLAYLIST_TOGGLE = 'SET_POPUP_PLAYLIST_TOGGLE';

export const SET_CONTEXTMENU_SHOW = 'SET_CONTEXTMENU_SHOW';

export const SET_CONTEXTMENU_SHARE_LINK = 'SET_CONTEXTMENU_SHARE_LINK';

export const SET_SEARCH_SHOW = 'SET_SEARCH_SHOW';

export const SET_DIALOG_SHARE_SHOW = 'SET_DIALOG_SHARE_SHOW';

export const SET_DIALOG_SHARE_WX_SHOW = 'SET_DIALOG_SHARE_WX_SHOW';

export const SET_DIALOG_UPLOAD_AVATAR_SHOW = 'SET_DIALOG_UPLOAD_AVATAR_SHOW';

export const SET_DIALOG_CREATE_PLAYLIST_SHOW = 'SET_DIALOG_CREATE_PLAYLIST_SHOW';

export const SET_DIALOG_UN_SUBSCRIPTION_SHOW = 'SET_DIALOG_UN_SUBSCRIPTION_SHOW';

export const SET_DIALOG_HOME_ORDER_SHOW = 'SET_DIALOG_HOME_ORDER_SHOW';

export const SET_DIALOG_RESET = 'SET_DIALOG_RESET';
