export const SET_FRIEND_INIT = 'SET_FRIEND_INIT';
export const SET_FRIEND_HOT = 'SET_FRIEND_HOT';
export const SET_FRIEND_EVENT = 'SET_FRIEND_EVENT';
export const SET_FRIEND_EVENT_ADD = 'SET_FRIEND_EVENT_ADD';
export const SET_FRIEND_EVENT_RESET = 'SET_FRIEND_EVENT_RESET';
export const SET_COMMENT_EVENT = 'SET_COMMENT_EVENT';
