// common
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_NOT_LOGIN = 'SET_NOT_LOGIN';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';

// user
export const SET_MSG_PRIVATE = 'SET_MSG_PRIVATE';
// home - recommend
export const SET_HOME_RECOMMEND = 'SET_HOME_RECOMMEND';
// home -dj
export const SET_HOME_DJ = 'SET_HOME_DJ';

export const SET_COUNTRIES_CODE_LIST = 'SET_COUNTRIES_CODE_LIST';

export const SET_LOGIN_VISIBILTY = 'SET_LOGIN_VISIBILTY';

export const GET_HOME_TOPLIST = 'GET_HOME_TOPLIST';

export const INIT_HOME_TOP_ARTISTS = 'INIT_HOME_TOP_ARTISTS';

export const ADD_HOME_TOP_ARTISTS = 'ADD_HOME_TOP_ARTISTS';

export const SET_TOPLIST_DETAIL = 'SET_TOPLIST_DETAIL';

export const SET_TOP_SONG = 'SET_TOP_SONG';

export const SET_TOP_ALBUM = 'SET_TOP_ALBUM';

export const SET_PLAYLIST_CATLIST = 'SET_PLAYLIST_CATLIST';
export const SET_TOP_PLAYLIST = 'SET_TOP_PLAYLIST';

export const SET_FRIEND_INIT = 'SET_FRIEND_INIT';
export const SET_FRIEND_EVENT = 'SET_FRIEND_EVENT';
export const SET_COMMENT_EVENT = 'SET_COMMENT_EVENT';

// common

export const SET_POPUP = 'SET_POPUP';

export const SET_LOCAL_CURRENT = 'SET_LOCAL_CURRENT';

export const SET_ARTIST_INIT = 'SET_ARTIST_INIT';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const SET_SEARCH_HOT = 'SET_SEARCH_HOT';

export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST';

export const SET_MSG_PRIVATE_HISTORY = 'SET_MSG_PRIVATE_HISTORY';

export const SET_TOAST = 'SET_TOAST';

export const SET_GLOBAL_INSET = 'SET_GLOBAL_INSET';

export const SET_CONTEXTMENU_SHOW = 'SET_CONTEXTMENU_SHOW';

export const SET_SEARCH_SHOW = 'SET_SEARCH_SHOW';

export const SET_DIALOG_SHARE_SHOW = 'SET_DIALOG_SHARE_SHOW';

export const SET_DIALOG_SHARE_WX_SHOW = 'SET_DIALOG_SHARE_WX_SHOW';

export const SET_DIALOG_UPLOAD_AVATAR_SHOW = 'SET_DIALOG_UPLOAD_AVATAR_SHOW';

export const SET_DIALOG_CREATE_PLAYLIST_SHOW = 'SET_DIALOG_CREATE_PLAYLIST_SHOW';

export const SET_DIALOG_RESET = 'SET_DIALOG_RESET';

// setting

export const SET_THEME = 'SET_THEME';

export const SET_VOLUME = 'SET_VOLUME';

export const SET_FONT = 'SET_FONT';

export const SET_SCREEN_FULL = 'SET_SCREEN_FULL';

// playlist
export const SET_AUDIO_IMMEDIATE = 'SET_AUDIO_IMMEDIATE';

export const SET_AUDIO_RUNNING_TOGGLE = 'SET_AUDIO_RUNNING_TOGGLE';

export const SET_AUDIO_CURRENTTIME = 'SET_AUDIO_CURRENTTIME';

export const SET_AUDIO_PLAYLIST_CLEAR = 'SET_AUDIO_PLAYLIST_CLEAR';

export const SET_AUDIO_HISTORY_CLEAR = 'SET_AUDIO_HISTORY_CLEAR';

export const SET_AUDIO_PATTERN = 'SET_AUDIO_PATTERN';
