// common
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_NOT_LOGIN = 'SET_NOT_LOGIN';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';
export const ADD_SONG_URL = 'ADD_SONG_URL';

// user
export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_RECORD = 'SET_USER_RECORD';
export const SET_MSG_PRIVATE = 'SET_MSG_PRIVATE';
// home - recommend
export const SET_HOME_RECOMMEND = 'SET_HOME_RECOMMEND';
// home -dj
export const SET_HOME_DJ = 'SET_HOME_DJ';

export const SET_COUNTRIES_CODE_LIST = 'SET_COUNTRIES_CODE_LIST';

export const SET_VIDEODETAIL_RELATED = 'SET_VIDEODETAIL_RELATED';

export const DIALOG_LOGIN_VISIBILTY = 'DIALOG_LOGIN_VISIBILTY';

export const GET_HOME_TOPLIST = 'GET_HOME_TOPLIST';

export const INIT_HOME_TOP_ARTISTS = 'INIT_HOME_TOP_ARTISTS';

export const ADD_HOME_TOP_ARTISTS = 'ADD_HOME_TOP_ARTISTS';

export const SET_TOPLIST_ARITST = 'SET_TOPLIST_ARITST';

export const SET_TOPLIST_DETAIL = 'SET_TOPLIST_DETAIL';

export const SET_TOP_SONG = 'SET_TOP_SONG';

export const SET_TOP_ALBUM = 'SET_TOP_ALBUM';

export const SET_PLAYLIST_CATLIST = 'SET_PLAYLIST_CATLIST';
export const SET_TOP_PLAYLIST = 'SET_TOP_PLAYLIST';

export const SET_PLAYLIST_DETAIL = 'SET_PLAYLIST_DETAIL';

export const SET_FRIEND_INIT = 'SET_FRIEND_INIT';
export const SET_FRIEND_EVENT = 'SET_FRIEND_EVENT';
export const SET_COMMENT_EVENT = 'SET_COMMENT_EVENT';

// common

export const SET_POPUP = 'SET_POPUP';
