// common
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_NOT_LOGIN = 'SET_NOT_LOGIN';

export const SET_MSG_PRIVATE = 'SET_MSG_PRIVATE';

export const SET_COUNTRIES_CODE_LIST = 'SET_COUNTRIES_CODE_LIST';

export const SET_LOGIN_VISIBILTY = 'SET_LOGIN_VISIBILTY';

export const GET_HOME_TOPLIST = 'GET_HOME_TOPLIST';
