export const SET_GLOBAL_INSET = 'SET_GLOBAL_INSET';
export const SET_GLOBAL_START_INSET = 'SET_GLOBAL_START_INSET';
export const SET_GLOBAL_DRAGGER = 'SET_GLOBAL_DRAGGER';
export const SET_GLOBAL_RESIZER = 'SET_GLOBAL_RESIZER';
export const SET_GLOBAL_START_RECT = 'SET_GLOBAL_START_RECT';
export const SET_GLOBAL_RECT = 'SET_GLOBAL_RECT';
export const SET_SCREEN_FULL = 'SET_SCREEN_FULL';
export const SET_SCREEN_NORMAL = 'SET_SCREEN_NORMAL';
export const SET_POSITION_TRUE = 'SET_POSITION_TRUE';
export const SET_POSITION_FALSE = 'SET_POSITION_FALSE';

export const SET_GLOBAL_LRC_INSET = 'SET_GLOBAL_LRC_INSET';
export const SET_GLOBAL_LRC_START_INSET = 'SET_GLOBAL_LRC_START_INSET';
