export const SET_LYRIC_TEXT = 'SET_LYRIC_TEXT';

export const SET_GLOBAL_LRC_TOGGLE = 'SET_GLOBAL_LRC_TOGGLE';
export const SET_GLOBAL_LRC_SHOW = 'SET_GLOBAL_LRC_SHOW';
export const SET_GLOBAL_LRC_HIDE = 'SET_GLOBAL_LRC_HIDE';

export const SET_LYRIC_SHOW = 'SET_LYRIC_SHOW';
export const SET_LYRIC_HIDE = 'SET_LYRIC_HIDE';
export const SET_LYRIC_TOGGLE = 'SET_LYRIC_TOGGLE';
