export const SET_EXCLUSIVE_RESULT_ADD = 'SET_EXCLUSIVE_RESULT_ADD';
export const SET_EXCLUSIVE_RESULT_EMPTY = 'SET_EXCLUSIVE_RESULT_EMPTY';
export const SET_EXCLUSIVE_SCROLLTOP = 'SET_EXCLUSIVE_SCROLLTOP';
