export const GET_VIDEO_GROUP_LIST = "GET_VIDEO_GROUP_LIST";

export const ADD_COUNT = "ADD_COUNT";

export const DIALOG_LOGIN_VISIBILTY = "DIALOG_LOGIN_VISIBILTY";

export const GET_HOME_TOPLIST = "GET_HOME_TOPLIST";

export const INIT_HOME_TOP_ARTISTS = "INIT_HOME_TOP_ARTISTS";

export const ADD_HOME_TOP_ARTISTS = "ADD_HOME_TOP_ARTISTS";

export const GET_TOPLIST_ARITST = 'GET_TOPLIST_ARITST'

export const GET_TOPLIST_DETAIL = 'GET_TOPLIST_DETAIL'

export const GET_TOP_SONG = 'GET_TOP_SONG'